server:
  port: 10002

spring:
  datasource:
    url: jdbc:mysql://1.94.47.104:3306/study_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123321Frq
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: study-system-boot3.x

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.furenqiang.system.entity
  global-config:
    db-column-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#robot:
#  age: 23
#  email: aa@xx.com
#  name: EricFRQ