server:
  port: 10002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  redis:
  #    host: 192.168.88.41
  #    port: 6379
  #    password: wellsun_2018
  #    database: 0
  #    timeout: 5000
  #    jedis:
  #      pool:
  #        max-active: 50
  #        max-wait: 3000
  #        max-idle: 20
  #        min-idle: 2
  #  session:
  #    store-type: redis
  #    timeout: 1800
  #    redis:
  #      namespace: wssf
  application:
    name: study-system
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  main:
#    allow-bean-definition-overriding: true
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.furenqiang.system.entity
  #
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://localhost:10030/eureka/  # 服务中心地址
  #
  #feign:
  #  httpclient:
  #    connection-timeout: 30000
  #  hystrix:
  #    enabled: true
  #
  #ribbon:
  #  ReadTimeout: 5000
  #  SocketTimeout: 5000
  #
  #hystrix:
  #  command:
  #    default:
  #      execution:
  #        isolation:
  #          thread:
  #            timeoutInMilliseconds: 12000
  #        timeout:
  #          enabled: false